volumes:
  postgres_data:

services:

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ragnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ragnet


  bootstrapper:
    build: ./backend

    command: >
      sh -c "
        echo REBUILD_EMBEDDINGS=$$REBUILD_EMBEDDINGS &&
        python -m app.bootstrapper
      "

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REBUILD_EMBEDDINGS: ${REBUILD_EMBEDDINGS}
      PDF_PATH: /app/sources

    volumes:
      - ./sources:/app/sources

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - ragnet


  frontend:
    build: ./frontend
    networks:
      - ragnet


  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - ragnet


networks:
  ragnet: